# Generated by Django 5.2.5 on 2025-08-31 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Becario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(help_text='PIN numérico único para fichar. Debe ser asignado manualmente.', max_length=8, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(help_text='Documento Nacional de Identidad.', max_length=15, unique=True)),
                ('horario_entrada_teorico', models.TimeField()),
                ('horario_salida_teorico', models.TimeField()),
                ('activo', models.BooleanField(default=True, help_text='Indica si el becario está actualmente activo en el programa.')),
            ],
            options={
                'verbose_name': 'Becario',
                'verbose_name_plural': 'Becarios',
            },
        ),
    ]
