# Generated by Django 5.2.5 on 2025-08-31 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marcacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.DateTimeField(help_text='Fecha y hora de entrada.')),
                ('salida', models.DateTimeField(blank=True, help_text='Fecha y hora de salida. Nulo si el becario aún no ha fichado la salida.', null=True)),
                ('estado', models.CharField(choices=[('CORRECTA', 'Correcta'), ('CIERRE_AUTOMATICO', 'Cierre Automático por Olvido'), ('REQUIERE_REVISION', 'Requiere Revisión'), ('CORREGIDA_ADMIN', 'Corregida por Admin')], default='CORRECTA', max_length=20)),
                ('observaciones_admin', models.TextField(blank=True, help_text='Notas del administrador sobre esta marcación (ej. motivo de corrección).')),
                ('becario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcaciones', to='usuarios.becario')),
            ],
            options={
                'verbose_name': 'Marcación',
                'verbose_name_plural': 'Marcaciones',
                'ordering': ['-entrada'],
            },
        ),
    ]
